"""Tests for daily task metadata used by Today and Daily Focus."""

from app.api.v1.daily_tasks import _daily_instructions_for_item
from app.models.plan import PlanItem


def test_daily_instructions_prefers_plan_metadata():
    """Daily scripts generated by plan_generate live in meta_json."""
    item = PlanItem(
        id="item-1",
        meta_json={"daily_instructions": "Read chapter 1 and write three notes."},
        details_json={"daily_instructions": "Fallback detail instruction."},
    )

    assert _daily_instructions_for_item(item) == "Read chapter 1 and write three notes."


def test_daily_instructions_falls_back_to_detail_metadata():
    """Older generated items can still serve daily scripts from details_json."""
    item = PlanItem(
        id="item-1",
        meta_json={},
        details_json={"daily_instructions": "Use the generated detail instructions."},
    )

    assert _daily_instructions_for_item(item) == "Use the generated detail instructions."
