"""add_roadmap_json_to_plans

Revision ID: 0ce4a541fbda
Revises: 9b5c130aa99e
Create Date: 2026-02-19 16:34:59.666666

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0ce4a541fbda'
down_revision: Union[str, None] = '9b5c130aa99e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plans', sa.Column('roadmap_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('plans', 'roadmap_json')
    # ### end Alembic commands ###
