"""add job tracking tables

Revision ID: 169b17ece78c
Revises: i5d6e7f8g9h0
Create Date: 2026-01-13 02:15:17.870562

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '169b17ece78c'
down_revision: Union[str, None] = 'i5d6e7f8g9h0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('idol_suggest_jobs',
    sa.Column('user_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('interests', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('step', sa.String(length=100), nullable=True),
    sa.Column('progress_percent', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('result_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_idol_suggest_jobs_user_id'), 'idol_suggest_jobs', ['user_id'], unique=False)
    op.create_table('plan_generation_jobs',
    sa.Column('user_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('idol_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('progress_percent', sa.Integer(), nullable=False),
    sa.Column('step', sa.String(length=100), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('target_age', sa.Integer(), nullable=False),
    sa.Column('duration_weeks', sa.Integer(), nullable=False),
    sa.Column('weekly_hours', sa.Integer(), nullable=False),
    sa.Column('focus', sa.String(length=200), nullable=True),
    sa.Column('plan_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['idol_id'], ['idols.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_plan_generation_jobs_user_id'), 'plan_generation_jobs', ['user_id'], unique=False)
    op.create_table('plan_item_detail_jobs',
    sa.Column('plan_item_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('user_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('step', sa.String(length=100), nullable=True),
    sa.Column('progress_percent', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('result_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['plan_item_id'], ['plan_items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_plan_item_detail_jobs_plan_item_id'), 'plan_item_detail_jobs', ['plan_item_id'], unique=False)
    op.create_index(op.f('ix_plan_item_detail_jobs_user_id'), 'plan_item_detail_jobs', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_plan_item_detail_jobs_user_id'), table_name='plan_item_detail_jobs')
    op.drop_index(op.f('ix_plan_item_detail_jobs_plan_item_id'), table_name='plan_item_detail_jobs')
    op.drop_table('plan_item_detail_jobs')
    op.drop_index(op.f('ix_plan_generation_jobs_user_id'), table_name='plan_generation_jobs')
    op.drop_table('plan_generation_jobs')
    op.drop_index(op.f('ix_idol_suggest_jobs_user_id'), table_name='idol_suggest_jobs')
    op.drop_table('idol_suggest_jobs')
    # ### end Alembic commands ###
