"""add guided learning phase

Revision ID: 4e91b83a38a2
Revises: 5f9760a07a67
Create Date: 2026-02-26 18:41:57.952107

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4e91b83a38a2'
down_revision: Union[str, None] = '5f9760a07a67'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE session_phase ADD VALUE IF NOT EXISTS 'guided_learning'")
    op.add_column('intake_sessions', sa.Column('learning_thread_id', sa.UUID(as_uuid=False), nullable=True))
    op.create_foreign_key(None, 'intake_sessions', 'chat_threads', ['learning_thread_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'intake_sessions', type_='foreignkey')
    op.drop_column('intake_sessions', 'learning_thread_id')
    # ### end Alembic commands ###
