"""add session phase and agentic columns

Revision ID: 5f9760a07a67
Revises: 0ce4a541fbda
Create Date: 2026-02-20 23:46:21.116043

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5f9760a07a67'
down_revision: Union[str, None] = '0ce4a541fbda'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE TYPE session_phase AS ENUM ('INTAKE', 'IDOL_SELECTION', 'INTERVIEW', 'COMPARISON', 'BLUEPRINT', 'COMPLETED')")
    op.add_column('intake_sessions', sa.Column('phase', postgresql.ENUM('INTAKE', 'IDOL_SELECTION', 'INTERVIEW', 'COMPARISON', 'BLUEPRINT', 'COMPLETED', name='session_phase'), nullable=True))
    op.add_column('intake_sessions', sa.Column('user_age', sa.Integer(), nullable=True))
    op.add_column('intake_sessions', sa.Column('user_financial_status', sa.String(length=500), nullable=True))
    op.add_column('intake_sessions', sa.Column('user_interests', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('intake_sessions', sa.Column('interview_thread_id', sa.UUID(as_uuid=False), nullable=True))
    op.add_column('intake_sessions', sa.Column('interview_turn_count', sa.Integer(), nullable=False))
    op.add_column('intake_sessions', sa.Column('idol_facts_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('intake_sessions', sa.Column('comparison_output', sa.Text(), nullable=True))
    op.add_column('intake_sessions', sa.Column('blueprint_output', sa.Text(), nullable=True))
    op.alter_column('intake_sessions', 'idol_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.create_index('ix_intake_sessions_phase', 'intake_sessions', ['phase'], unique=False)
    op.create_index('ix_intake_sessions_user_phase', 'intake_sessions', ['user_id', 'phase'], unique=False)
    op.create_foreign_key(None, 'intake_sessions', 'chat_threads', ['interview_thread_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'intake_sessions', type_='foreignkey')
    op.drop_index('ix_intake_sessions_user_phase', table_name='intake_sessions')
    op.drop_index('ix_intake_sessions_phase', table_name='intake_sessions')
    op.alter_column('intake_sessions', 'idol_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('intake_sessions', 'blueprint_output')
    op.drop_column('intake_sessions', 'comparison_output')
    op.drop_column('intake_sessions', 'idol_facts_json')
    op.drop_column('intake_sessions', 'interview_turn_count')
    op.drop_column('intake_sessions', 'interview_thread_id')
    op.drop_column('intake_sessions', 'user_interests')
    op.drop_column('intake_sessions', 'user_financial_status')
    op.drop_column('intake_sessions', 'user_age')
    op.drop_column('intake_sessions', 'phase')
    op.execute("DROP TYPE session_phase")
    # ### end Alembic commands ###
