"""Add image_url to Idol

Revision ID: 95b80fff118f
Revises: c6267a502c34
Create Date: 2026-01-15 23:56:50.211800

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '95b80fff118f'
down_revision: Union[str, None] = 'c6267a502c34'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('idols', sa.Column('image_url', sa.String(length=1024), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('idols', 'image_url')
    # ### end Alembic commands ###
