"""add updated_at to plan_items

Revision ID: a38bc9f11f7b
Revises: d9ebecb11d6e
Create Date: 2026-01-05 19:25:03.033094

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a38bc9f11f7b'
down_revision: Union[str, None] = 'd9ebecb11d6e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plan_items', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('plan_items', 'updated_at')
    # ### end Alembic commands ###
