"""add_thinking_text_to_job_tables

Revision ID: c6267a502c34
Revises: 169b17ece78c
Create Date: 2026-01-13 20:22:44.679911

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c6267a502c34'
down_revision: Union[str, None] = '169b17ece78c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('idol_import_jobs', sa.Column('thinking_text', sa.Text(), nullable=True))
    op.add_column('idol_suggest_jobs', sa.Column('thinking_text', sa.Text(), nullable=True))
    op.add_column('plan_generation_jobs', sa.Column('thinking_text', sa.Text(), nullable=True))
    op.add_column('plan_item_detail_jobs', sa.Column('thinking_text', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('plan_item_detail_jobs', 'thinking_text')
    op.drop_column('plan_generation_jobs', 'thinking_text')
    op.drop_column('idol_suggest_jobs', 'thinking_text')
    op.drop_column('idol_import_jobs', 'thinking_text')
    # ### end Alembic commands ###
