"""add summary_text to idol_sources

Revision ID: c69c025017c3
Revises: 51e40a795d5b
Create Date: 2026-01-05 17:42:53.258015

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c69c025017c3'
down_revision: Union[str, None] = '51e40a795d5b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('idol_sources', sa.Column('summary_text', sa.Text(), nullable=True))
    op.add_column('idol_sources', sa.Column('full_text', sa.Text(), nullable=False))
    op.drop_column('idol_sources', 'raw_text')
    # Constraint uq_idol_tag already exists from previous migration
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('idol_sources', sa.Column('raw_text', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_column('idol_sources', 'full_text')
    op.drop_column('idol_sources', 'summary_text')
    # ### end Alembic commands ###
