"""add user_achievements plans notes chat tables

Revision ID: d9ebecb11d6e
Revises: f036cafdc9d3
Create Date: 2026-01-05 19:00:36.538323

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd9ebecb11d6e'
down_revision: Union[str, None] = 'f036cafdc9d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_threads',
    sa.Column('user_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('idol_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['idol_id'], ['idols.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_threads_idol_id'), 'chat_threads', ['idol_id'], unique=False)
    op.create_index(op.f('ix_chat_threads_user_id'), 'chat_threads', ['user_id'], unique=False)
    op.create_table('notes',
    sa.Column('user_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notes_user_id'), 'notes', ['user_id'], unique=False)
    op.create_table('plans',
    sa.Column('user_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('idol_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('target_age', sa.Integer(), nullable=False),
    sa.Column('duration_weeks', sa.Integer(), nullable=False),
    sa.Column('weekly_hours', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['idol_id'], ['idols.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_plans_user_id'), 'plans', ['user_id'], unique=False)
    op.create_table('user_achievements',
    sa.Column('user_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('category', sa.Enum('CAREER', 'LEARNING', 'FINANCE', 'IMPACT', 'MINDSET', 'OTHER', name='user_achievement_category'), nullable=False),
    sa.Column('achievement_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('evidence_link', sa.String(length=2048), nullable=True),
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_achievements_user_id'), 'user_achievements', ['user_id'], unique=False)
    op.create_table('chat_messages',
    sa.Column('thread_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('role', sa.Enum('USER', 'ASSISTANT', name='message_role'), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['thread_id'], ['chat_threads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_messages_thread_id'), 'chat_messages', ['thread_id'], unique=False)
    op.create_table('plan_items',
    sa.Column('plan_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('type', sa.Enum('HABIT', 'PROJECT', 'READING', 'COURSE', 'PRACTICE', 'REFLECTION', name='plan_item_type'), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('week_start', sa.Integer(), nullable=False),
    sa.Column('week_end', sa.Integer(), nullable=False),
    sa.Column('success_metric', sa.String(length=300), nullable=False),
    sa.Column('estimated_hours', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('NOT_STARTED', 'IN_PROGRESS', 'COMPLETED', 'SKIPPED', name='plan_item_status'), nullable=False),
    sa.Column('progress_percent', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('resource_title', sa.String(length=300), nullable=True),
    sa.Column('resource_url', sa.String(length=2048), nullable=True),
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_plan_items_plan_id'), 'plan_items', ['plan_id'], unique=False)
    op.create_table('note_attachments',
    sa.Column('note_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('idol_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('plan_item_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('achievement_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['achievement_id'], ['user_achievements.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['idol_id'], ['idols.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['note_id'], ['notes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['plan_item_id'], ['plan_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_note_attachments_note_id'), 'note_attachments', ['note_id'], unique=False)
    # uq_idol_tag constraint already exists from earlier migration
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_note_attachments_note_id'), table_name='note_attachments')
    op.drop_table('note_attachments')
    op.drop_index(op.f('ix_plan_items_plan_id'), table_name='plan_items')
    op.drop_table('plan_items')
    op.drop_index(op.f('ix_chat_messages_thread_id'), table_name='chat_messages')
    op.drop_table('chat_messages')
    op.drop_index(op.f('ix_user_achievements_user_id'), table_name='user_achievements')
    op.drop_table('user_achievements')
    op.drop_index(op.f('ix_plans_user_id'), table_name='plans')
    op.drop_table('plans')
    op.drop_index(op.f('ix_notes_user_id'), table_name='notes')
    op.drop_table('notes')
    op.drop_index(op.f('ix_chat_threads_user_id'), table_name='chat_threads')
    op.drop_index(op.f('ix_chat_threads_idol_id'), table_name='chat_threads')
    op.drop_table('chat_threads')
    # ### end Alembic commands ###
