"""add idol_profiles idol_timeline_events idol_personas

Revision ID: f036cafdc9d3
Revises: c69c025017c3
Create Date: 2026-01-05 18:32:03.251233

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f036cafdc9d3'
down_revision: Union[str, None] = 'c69c025017c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('idol_personas',
    sa.Column('idol_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('voice_style', sa.Text(), nullable=False),
    sa.Column('principles', postgresql.ARRAY(sa.String(length=500)), nullable=False),
    sa.Column('dos', postgresql.ARRAY(sa.String(length=500)), nullable=False),
    sa.Column('donts', postgresql.ARRAY(sa.String(length=500)), nullable=False),
    sa.Column('signature_phrases', postgresql.ARRAY(sa.String(length=500)), nullable=False),
    sa.Column('topics_of_strength', postgresql.ARRAY(sa.String(length=200)), nullable=False),
    sa.Column('taboo_topics', postgresql.ARRAY(sa.String(length=200)), nullable=False),
    sa.Column('grounding_evidence', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('disclaimer', sa.Text(), nullable=False),
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['idol_id'], ['idols.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idol_id')
    )
    op.create_table('idol_profiles',
    sa.Column('idol_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('short_description', sa.Text(), nullable=True),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('death_date', sa.Date(), nullable=True),
    sa.Column('nationality', postgresql.ARRAY(sa.String(length=100)), nullable=False),
    sa.Column('domains', postgresql.ARRAY(sa.String(length=100)), nullable=False),
    sa.Column('primary_roles', postgresql.ARRAY(sa.String(length=100)), nullable=False),
    sa.Column('era_tags', postgresql.ARRAY(sa.String(length=100)), nullable=False),
    sa.Column('notable_themes', postgresql.ARRAY(sa.String(length=100)), nullable=False),
    sa.Column('wikipedia_url', sa.String(length=2048), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('evidence', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['idol_id'], ['idols.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idol_id')
    )
    op.create_table('idol_timeline_events',
    sa.Column('idol_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('canonical_title', sa.String(length=200), nullable=False),
    sa.Column('canonical_description', sa.Text(), nullable=False),
    sa.Column('event_date', sa.Date(), nullable=True),
    sa.Column('date_precision', sa.Enum('DAY', 'MONTH', 'YEAR', 'UNKNOWN', name='date_precision_enum'), nullable=False),
    sa.Column('age_at_event', sa.Integer(), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('importance_score', sa.Float(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('evidence', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['idol_id'], ['idols.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_idol_timeline_events_idol_id'), 'idol_timeline_events', ['idol_id'], unique=False)
    # uq_idol_tag constraint already exists from earlier migration
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_idol_timeline_events_idol_id'), table_name='idol_timeline_events')
    op.drop_table('idol_timeline_events')
    op.drop_table('idol_profiles')
    op.drop_table('idol_personas')
    # ### end Alembic commands ###
