"""Plan and PlanItem models for development plans."""
from datetime import datetime
from enum import Enum
from typing import TYPE_CHECKING

from sqlalchemy import DateTime, Enum as SQLEnum, ForeignKey, Index, Integer, String, Text, UniqueConstraint
from sqlalchemy.dialects.postgresql import JSONB, UUID
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.models.base import Base, UUIDMixin, TimestampMixin, TimestampUpdateMixin

if TYPE_CHECKING:
    from app.models.user import User
    from app.models.idol import Idol
    from app.models.content_resource import ContentResource


class PlanItemType(str, Enum):
    HABIT = "habit"
    PROJECT = "project"
    READING = "reading"
    COURSE = "course"
    PRACTICE = "practice"
    REFLECTION = "reflection"


class PlanItemStatus(str, Enum):
    NOT_STARTED = "not_started"
    IN_PROGRESS = "in_progress"
    COMPLETED = "completed"
    SKIPPED = "skipped"


class Plan(Base, UUIDMixin, TimestampMixin):
    """
    A development plan for a user to close gaps vs their idol.
    """
    __tablename__ = "plans"

    user_id: Mapped[str] = mapped_column(
        UUID(as_uuid=False),
        ForeignKey("users.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    idol_id: Mapped[str] = mapped_column(
        UUID(as_uuid=False),
        ForeignKey("idols.id", ondelete="SET NULL"),
        nullable=True,
    )
    
    target_age: Mapped[int] = mapped_column(Integer, nullable=False)
    duration_weeks: Mapped[int] = mapped_column(Integer, nullable=False, default=12)
    weekly_hours: Mapped[int] = mapped_column(Integer, nullable=False, default=10)
    cycle_number: Mapped[int] = mapped_column(Integer, nullable=False, default=1)
    completed_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True), nullable=True
    )
    previous_plan_id: Mapped[str | None] = mapped_column(
        UUID(as_uuid=False),
        ForeignKey("plans.id", ondelete="SET NULL"),
        nullable=True,
    )

    # New: stores roadmap_thesis and anti_goals from plan_generate.txt
    # Structure: { "roadmap_thesis": "...", "anti_goals": ["..."] }
    roadmap_json: Mapped[dict | None] = mapped_column(JSONB, nullable=True)
    
    # Relationships
    user: Mapped["User"] = relationship("User", back_populates="plans", lazy="selectin")
    idol: Mapped["Idol | None"] = relationship("Idol", lazy="selectin")
    items: Mapped[list["PlanItem"]] = relationship(
        "PlanItem", back_populates="plan", cascade="all, delete-orphan", lazy="selectin"
    )


class PlanItem(Base, UUIDMixin, TimestampUpdateMixin):
    """
    Individual item in a development plan.
    """
    __tablename__ = "plan_items"

    plan_id: Mapped[str] = mapped_column(
        UUID(as_uuid=False),
        ForeignKey("plans.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    
    title: Mapped[str] = mapped_column(String(200), nullable=False)
    type: Mapped[PlanItemType] = mapped_column(
        SQLEnum(PlanItemType, name="plan_item_type"),
        nullable=False,
        default=PlanItemType.PROJECT,
    )
    description: Mapped[str] = mapped_column(Text, nullable=False)
    
    week_start: Mapped[int] = mapped_column(Integer, nullable=False, default=1)
    week_end: Mapped[int] = mapped_column(Integer, nullable=False, default=1)
    success_metric: Mapped[str] = mapped_column(String(300), nullable=False)
    estimated_hours: Mapped[int] = mapped_column(Integer, nullable=False, default=0)
    
    status: Mapped[PlanItemStatus] = mapped_column(
        SQLEnum(PlanItemStatus, name="plan_item_status"),
        nullable=False,
        default=PlanItemStatus.NOT_STARTED,
    )
    progress_percent: Mapped[int] = mapped_column(Integer, nullable=False, default=0)
    notes: Mapped[str | None] = mapped_column(Text, nullable=True)
    
    # Optional resource
    resource_title: Mapped[str | None] = mapped_column(String(300), nullable=True)
    resource_url: Mapped[str | None] = mapped_column(String(2048), nullable=True)
    
    # Detailed steps and materials (generated by LLM)
    # Structure: { steps: [{id, title, description}...], materials: [{title, url, type}...], 
    #              generated_from_prompt_version: "...", generated_at: "..." }
    details_json: Mapped[dict | None] = mapped_column(JSONB, nullable=True)
    
    # Metadata from plan generation (used by plan_item_details.txt)
    # Structure: { detail_tags: [...], primary_gap: "...", suggested_queries: [...], idol_parallel: "..." }
    meta_json: Mapped[dict | None] = mapped_column(JSONB, nullable=True)
    
    # Relationships
    plan: Mapped["Plan"] = relationship("Plan", back_populates="items")
    step_completions: Mapped[list["PlanItemStepCompletion"]] = relationship(
        "PlanItemStepCompletion", back_populates="plan_item", cascade="all, delete-orphan"
    )
    completions: Mapped[list["PlanItemCompletion"]] = relationship(
        "PlanItemCompletion", back_populates="plan_item", cascade="all, delete-orphan"
    )
    content_resource_links: Mapped[list["PlanItemContentResource"]] = relationship(
        "PlanItemContentResource",
        back_populates="plan_item",
        cascade="all, delete-orphan",
    )


class PlanItemContentResource(Base, UUIDMixin, TimestampMixin):
    """Plan material link pointing at a shared reusable content resource."""

    __tablename__ = "plan_item_content_resources"
    __table_args__ = (
        UniqueConstraint(
            "plan_item_id",
            "content_resource_id",
            "material_index",
            name="uq_plan_item_content_resource_material",
        ),
        Index("ix_plan_item_content_resources_plan_item", "plan_item_id"),
        Index("ix_plan_item_content_resources_resource", "content_resource_id"),
    )

    plan_item_id: Mapped[str] = mapped_column(
        UUID(as_uuid=False),
        ForeignKey("plan_items.id", ondelete="CASCADE"),
        nullable=False,
    )
    content_resource_id: Mapped[str] = mapped_column(
        UUID(as_uuid=False),
        ForeignKey("content_resources.id", ondelete="CASCADE"),
        nullable=False,
    )
    material_index: Mapped[int] = mapped_column(Integer, nullable=False, default=0)
    material_type: Mapped[str | None] = mapped_column(String(80), nullable=True)
    title: Mapped[str | None] = mapped_column(String(300), nullable=True)
    canonical_key: Mapped[str | None] = mapped_column(String(320), nullable=True)
    metadata_json: Mapped[dict | None] = mapped_column(JSONB, nullable=True)

    plan_item: Mapped["PlanItem"] = relationship(
        "PlanItem",
        back_populates="content_resource_links",
    )
    content_resource: Mapped["ContentResource"] = relationship("ContentResource")

class PlanItemStepCompletion(Base, UUIDMixin):
    """
    Per-user step-level completion tracking for plan items.
    
    Each record represents a user completing a specific step within a plan item.
    """
    __tablename__ = "plan_item_step_completions"
    __table_args__ = (
        Index(
            "ix_plan_item_step_completions_unique",
            "user_id", "plan_item_id", "step_id",
            unique=True,
        ),
    )

    user_id: Mapped[str] = mapped_column(
        UUID(as_uuid=False),
        ForeignKey("users.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    plan_item_id: Mapped[str] = mapped_column(
        UUID(as_uuid=False),
        ForeignKey("plan_items.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    step_id: Mapped[str] = mapped_column(String(100), nullable=False)
    completed_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True), nullable=True
    )

    # Relationships
    user: Mapped["User"] = relationship("User")
    plan_item: Mapped["PlanItem"] = relationship("PlanItem", back_populates="step_completions")


class PlanItemCompletion(Base, UUIDMixin):
    """
    Per-user item-level completion tracking for plan items.
    
    Each record represents a user completing an entire plan item.
    """
    __tablename__ = "plan_item_completions"
    __table_args__ = (
        Index(
            "ix_plan_item_completions_unique",
            "user_id", "plan_item_id",
            unique=True,
        ),
    )

    user_id: Mapped[str] = mapped_column(
        UUID(as_uuid=False),
        ForeignKey("users.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    plan_item_id: Mapped[str] = mapped_column(
        UUID(as_uuid=False),
        ForeignKey("plan_items.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    completed_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True), nullable=True
    )

    # Relationships
    user: Mapped["User"] = relationship("User")
    plan_item: Mapped["PlanItem"] = relationship("PlanItem", back_populates="completions")
